name: flutter_hi_http
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  fluttertoast: ^8.2.12
  flutter_swiper_null_safety_flutter3: ^4.0.3
  flutter_staggered_grid_view: ^0.7.0
  transparent_image: ^2.0.1
  cached_network_image: ^3.4.1
  chewie: ^1.11.3
  video_player: ^2.9.5
  intl: ^0.20.2
  web_socket_channel: ^3.0.3
  flutter_riverpod: ^2.6.1
  go_router: ^15.2.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  assets:
    - images/

